export interface SeedSkill {
  id: string;
  name: string;
  category: 'Frontend' | 'Backend' | 'Database' | 'DevOps & Cloud' | 'Data & AI' | 'Core Engineering';
}

export interface SeedCompany {
  id: string;
  name: string;
  industry: string;
  description: string;
  locationId: string;
}

export interface SeedLocation {
  id: string;
  city: string;
  country: string;
}

export interface SeedJob {
  id: string;
  title: string;
  description: string;
  employmentType: 'Full-time' | 'Part-time' | 'Contract' | 'Remote';
  experienceLevel: 'Entry' | 'Mid' | 'Senior' | 'Lead';
  salaryMin: number;
  salaryMax: number;
  companyId: string;
  locationId: string;
  requiredSkillIds: string[];
}

export interface SeedUser {
  id: string;
  name: string;
  email: string;
  skillIds: string[];
}

export interface SeedSkillRelation {
  fromSkillId: string;
  toSkillId: string;
  weight?: number;
}

export const locations: SeedLocation[] = [
  { id: 'loc-sf', city: 'San Francisco', country: 'United States' },
  { id: 'loc-ny', city: 'New York', country: 'United States' },
  { id: 'loc-sea', city: 'Seattle', country: 'United States' },
  { id: 'loc-aus', city: 'Austin', country: 'United States' },
  { id: 'loc-lon', city: 'London', country: 'United Kingdom' },
  { id: 'loc-ber', city: 'Berlin', country: 'Germany' },
  { id: 'loc-tor', city: 'Toronto', country: 'Canada' },
  { id: 'loc-blr', city: 'Bangalore', country: 'India' },
  { id: 'loc-tok', city: 'Tokyo', country: 'Japan' },
  { id: 'loc-rem', city: 'Remote', country: 'Global' },
];

export const skills: SeedSkill[] = [
  // Frontend
  { id: 'skill-js', name: 'JavaScript', category: 'Frontend' },
  { id: 'skill-ts', name: 'TypeScript', category: 'Frontend' },
  { id: 'skill-react', name: 'React', category: 'Frontend' },
  { id: 'skill-nextjs', name: 'Next.js', category: 'Frontend' },
  { id: 'skill-vue', name: 'Vue.js', category: 'Frontend' },
  { id: 'skill-angular', name: 'Angular', category: 'Frontend' },
  { id: 'skill-html', name: 'HTML5', category: 'Frontend' },
  { id: 'skill-css', name: 'CSS3', category: 'Frontend' },
  { id: 'skill-tailwind', name: 'Tailwind CSS', category: 'Frontend' },
  { id: 'skill-redux', name: 'Redux', category: 'Frontend' },

  // Backend
  { id: 'skill-node', name: 'Node.js', category: 'Backend' },
  { id: 'skill-express', name: 'Express', category: 'Backend' },
  { id: 'skill-nest', name: 'NestJS', category: 'Backend' },
  { id: 'skill-python', name: 'Python', category: 'Backend' },
  { id: 'skill-django', name: 'Django', category: 'Backend' },
  { id: 'skill-fastapi', name: 'FastAPI', category: 'Backend' },
  { id: 'skill-java', name: 'Java', category: 'Backend' },
  { id: 'skill-spring', name: 'Spring Boot', category: 'Backend' },
  { id: 'skill-go', name: 'Go', category: 'Backend' },
  { id: 'skill-rust', name: 'Rust', category: 'Backend' },
  { id: 'skill-csharp', name: 'C#', category: 'Backend' },
  { id: 'skill-dotnet', name: '.NET Core', category: 'Backend' },
  { id: 'skill-rest', name: 'REST APIs', category: 'Backend' },
  { id: 'skill-graphql', name: 'GraphQL', category: 'Backend' },
  { id: 'skill-grpc', name: 'gRPC', category: 'Backend' },

  // Database
  { id: 'skill-sql', name: 'SQL', category: 'Database' },
  { id: 'skill-postgres', name: 'PostgreSQL', category: 'Database' },
  { id: 'skill-mysql', name: 'MySQL', category: 'Database' },
  { id: 'skill-mongodb', name: 'MongoDB', category: 'Database' },
  { id: 'skill-redis', name: 'Redis', category: 'Database' },
  { id: 'skill-elastic', name: 'Elasticsearch', category: 'Database' },
  { id: 'skill-neo4j', name: 'Neo4j / Graph Databases', category: 'Database' },
  { id: 'skill-kafka', name: 'Apache Kafka', category: 'Database' },

  // DevOps & Cloud
  { id: 'skill-docker', name: 'Docker', category: 'DevOps & Cloud' },
  { id: 'skill-k8s', name: 'Kubernetes', category: 'DevOps & Cloud' },
  { id: 'skill-aws', name: 'AWS', category: 'DevOps & Cloud' },
  { id: 'skill-gcp', name: 'Google Cloud (GCP)', category: 'DevOps & Cloud' },
  { id: 'skill-azure', name: 'Microsoft Azure', category: 'DevOps & Cloud' },
  { id: 'skill-terraform', name: 'Terraform', category: 'DevOps & Cloud' },
  { id: 'skill-cicd', name: 'CI/CD Pipelines', category: 'DevOps & Cloud' },
  { id: 'skill-linux', name: 'Linux System Admin', category: 'DevOps & Cloud' },
  { id: 'skill-prometheus', name: 'Prometheus & Grafana', category: 'DevOps & Cloud' },

  // Data & AI
  { id: 'skill-pandas', name: 'Pandas', category: 'Data & AI' },
  { id: 'skill-numpy', name: 'NumPy', category: 'Data & AI' },
  { id: 'skill-spark', name: 'Apache Spark', category: 'Data & AI' },
  { id: 'skill-powerbi', name: 'Power BI', category: 'Data & AI' },
  { id: 'skill-tableau', name: 'Tableau', category: 'Data & AI' },
  { id: 'skill-pytorch', name: 'PyTorch', category: 'Data & AI' },
  { id: 'skill-tensorflow', name: 'TensorFlow', category: 'Data & AI' },
  { id: 'skill-llm', name: 'LLM & LangChain', category: 'Data & AI' },

  // Core Engineering
  { id: 'skill-git', name: 'Git', category: 'Core Engineering' },
  { id: 'skill-microservices', name: 'Microservices Architecture', category: 'Core Engineering' },
  { id: 'skill-sysdesign', name: 'System Design', category: 'Core Engineering' },
  { id: 'skill-testing', name: 'Unit & E2E Testing (Jest/Playwright)', category: 'Core Engineering' },
];

export const skillRelations: SeedSkillRelation[] = [
  // Frontend relations
  { fromSkillId: 'skill-js', toSkillId: 'skill-ts' },
  { fromSkillId: 'skill-js', toSkillId: 'skill-react' },
  { fromSkillId: 'skill-js', toSkillId: 'skill-vue' },
  { fromSkillId: 'skill-js', toSkillId: 'skill-node' },
  { fromSkillId: 'skill-react', toSkillId: 'skill-nextjs' },
  { fromSkillId: 'skill-react', toSkillId: 'skill-redux' },
  { fromSkillId: 'skill-react', toSkillId: 'skill-tailwind' },
  { fromSkillId: 'skill-ts', toSkillId: 'skill-react' },
  { fromSkillId: 'skill-ts', toSkillId: 'skill-nest' },
  { fromSkillId: 'skill-html', toSkillId: 'skill-css' },
  { fromSkillId: 'skill-html', toSkillId: 'skill-js' },
  { fromSkillId: 'skill-css', toSkillId: 'skill-tailwind' },

  // Backend relations
  { fromSkillId: 'skill-node', toSkillId: 'skill-express' },
  { fromSkillId: 'skill-node', toSkillId: 'skill-nest' },
  { fromSkillId: 'skill-node', toSkillId: 'skill-ts' },
  { fromSkillId: 'skill-express', toSkillId: 'skill-rest' },
  { fromSkillId: 'skill-python', toSkillId: 'skill-django' },
  { fromSkillId: 'skill-python', toSkillId: 'skill-fastapi' },
  { fromSkillId: 'skill-python', toSkillId: 'skill-pandas' },
  { fromSkillId: 'skill-python', toSkillId: 'skill-numpy' },
  { fromSkillId: 'skill-fastapi', toSkillId: 'skill-rest' },
  { fromSkillId: 'skill-java', toSkillId: 'skill-spring' },
  { fromSkillId: 'skill-csharp', toSkillId: 'skill-dotnet' },
  { fromSkillId: 'skill-go', toSkillId: 'skill-grpc' },
  { fromSkillId: 'skill-go', toSkillId: 'skill-microservices' },
  { fromSkillId: 'skill-rest', toSkillId: 'skill-graphql' },
  { fromSkillId: 'skill-rest', toSkillId: 'skill-grpc' },

  // Database relations
  { fromSkillId: 'skill-sql', toSkillId: 'skill-postgres' },
  { fromSkillId: 'skill-sql', toSkillId: 'skill-mysql' },
  { fromSkillId: 'skill-postgres', toSkillId: 'skill-redis' },
  { fromSkillId: 'skill-mongodb', toSkillId: 'skill-node' },
  { fromSkillId: 'skill-redis', toSkillId: 'skill-microservices' },
  { fromSkillId: 'skill-neo4j', toSkillId: 'skill-sql' },
  { fromSkillId: 'skill-kafka', toSkillId: 'skill-microservices' },
  { fromSkillId: 'skill-elastic', toSkillId: 'skill-postgres' },

  // DevOps / Cloud relations
  { fromSkillId: 'skill-docker', toSkillId: 'skill-k8s' },
  { fromSkillId: 'skill-docker', toSkillId: 'skill-aws' },
  { fromSkillId: 'skill-docker', toSkillId: 'skill-cicd' },
  { fromSkillId: 'skill-k8s', toSkillId: 'skill-terraform' },
  { fromSkillId: 'skill-aws', toSkillId: 'skill-terraform' },
  { fromSkillId: 'skill-aws', toSkillId: 'skill-gcp' },
  { fromSkillId: 'skill-aws', toSkillId: 'skill-azure' },
  { fromSkillId: 'skill-linux', toSkillId: 'skill-docker' },
  { fromSkillId: 'skill-k8s', toSkillId: 'skill-prometheus' },

  // Data / AI relations
  { fromSkillId: 'skill-pandas', toSkillId: 'skill-numpy' },
  { fromSkillId: 'skill-pandas', toSkillId: 'skill-spark' },
  { fromSkillId: 'skill-pandas', toSkillId: 'skill-powerbi' },
  { fromSkillId: 'skill-powerbi', toSkillId: 'skill-tableau' },
  { fromSkillId: 'skill-python', toSkillId: 'skill-pytorch' },
  { fromSkillId: 'skill-pytorch', toSkillId: 'skill-tensorflow' },
  { fromSkillId: 'skill-pytorch', toSkillId: 'skill-llm' },

  // Core Engineering
  { fromSkillId: 'skill-git', toSkillId: 'skill-cicd' },
  { fromSkillId: 'skill-microservices', toSkillId: 'skill-sysdesign' },
  { fromSkillId: 'skill-node', toSkillId: 'skill-testing' },
  { fromSkillId: 'skill-react', toSkillId: 'skill-testing' },
];

export const companies: SeedCompany[] = [
  { id: 'comp-stripe', name: 'Stripe', industry: 'Fintech & Payments', description: 'Financial infrastructure platform for the internet.', locationId: 'loc-sf' },
  { id: 'comp-vercel', name: 'Vercel', industry: 'Cloud & Developer Tools', description: 'Frontend Cloud platform for frameworks like Next.js and Svelte.', locationId: 'loc-sf' },
  { id: 'comp-datadog', name: 'Datadog', industry: 'Observability & Cloud', description: 'Monitoring and security platform for cloud-scale applications.', locationId: 'loc-ny' },
  { id: 'comp-shopify', name: 'Shopify', industry: 'E-commerce', description: 'Global commerce platform powering millions of businesses.', locationId: 'loc-tor' },
  { id: 'comp-github', name: 'GitHub', industry: 'Developer Tools', description: 'The complete developer platform to build, scale, and deliver software.', locationId: 'loc-sf' },
  { id: 'comp-linear', name: 'Linear', industry: 'Productivity Software', description: 'Modern issue tracking and project planning built for high-performance teams.', locationId: 'loc-rem' },
  { id: 'comp-supabase', name: 'Supabase', industry: 'Database & Cloud', description: 'Open source Firebase alternative with Postgres and instant APIs.', locationId: 'loc-rem' },
  { id: 'comp-cloudflare', name: 'Cloudflare', industry: 'Cybersecurity & CDN', description: 'Global network designed to make everything connected to the Internet secure and fast.', locationId: 'loc-aus' },
  { id: 'comp-openai', name: 'OpenAI', industry: 'Artificial Intelligence', description: 'AI research and deployment company pioneering frontier LLM models.', locationId: 'loc-sf' },
  { id: 'comp-mongodb', name: 'MongoDB', industry: 'Database Systems', description: 'Leading modern, general purpose data platform.', locationId: 'loc-ny' },
  { id: 'comp-notion', name: 'Notion', industry: 'Productivity & AI', description: 'Connected workspace where better, faster work happens.', locationId: 'loc-sf' },
  { id: 'comp-airbnb', name: 'Airbnb', industry: 'Travel & Marketplaces', description: 'Global platform connecting travelers with unique accommodations.', locationId: 'loc-sf' },
  { id: 'comp-spotify', name: 'Spotify', industry: 'Audio & Streaming', description: 'Audio streaming and media services provider with world-class algorithms.', locationId: 'loc-lon' },
  { id: 'comp-uber', name: 'Uber', industry: 'Mobility & Logistics', description: 'Platform revolutionizing mobility, freight, and urban delivery.', locationId: 'loc-sf' },
  { id: 'comp-coinbase', name: 'Coinbase', industry: 'Crypto & Web3', description: 'Secure platform that makes it easy to buy, sell, and store cryptocurrency.', locationId: 'loc-rem' },
  { id: 'comp-palantir', name: 'Palantir Technologies', industry: 'Enterprise Big Data', description: 'Software platforms for data integration and decision making.', locationId: 'loc-ny' },
  { id: 'comp-hashicorp', name: 'HashiCorp', industry: 'Infrastructure & DevOps', description: 'Cloud infrastructure automation software including Terraform and Vault.', locationId: 'loc-sea' },
  { id: 'comp-plaid', name: 'Plaid', industry: 'Financial Data APIs', description: 'Data network powering the fintech apps millions of people rely on.', locationId: 'loc-sf' },
  { id: 'comp-anthropic', name: 'Anthropic', industry: 'AI Safety & Research', description: 'AI research and safety company dedicated to building reliable AI systems.', locationId: 'loc-sf' },
  { id: 'comp-databricks', name: 'Databricks', industry: 'Data Intelligence', description: 'Unified platform for data engineering, analytics, and machine learning.', locationId: 'loc-sf' },
  { id: 'comp-snowflake', name: 'Snowflake', industry: 'Cloud Data Warehouse', description: 'Cloud computing-based data cloud platform.', locationId: 'loc-aus' },
  { id: 'comp-figma', name: 'Figma', industry: 'Design & Collaboration', description: 'Collaborative web application for interface design and prototyping.', locationId: 'loc-sf' },
  { id: 'comp-revolut', name: 'Revolut', industry: 'Digital Banking', description: 'Global financial super-app offering banking and investment services.', locationId: 'loc-lon' },
  { id: 'comp-zalando', name: 'Zalando', industry: 'Fashion E-commerce', description: 'Leading European online platform for fashion and lifestyle.', locationId: 'loc-ber' },
  { id: 'comp-swiggy', name: 'Swiggy', industry: 'On-Demand Delivery', description: 'Convenience commerce platform serving millions across India.', locationId: 'loc-blr' },
];

export const users: SeedUser[] = [
  {
    id: 'user-1',
    name: 'Alex Rivera',
    email: 'alex.rivera@example.com',
    skillIds: ['skill-js', 'skill-ts', 'skill-react', 'skill-nextjs', 'skill-tailwind', 'skill-html', 'skill-css'],
  },
  {
    id: 'user-2',
    name: 'Sarah Chen',
    email: 'sarah.chen@example.com',
    skillIds: ['skill-python', 'skill-fastapi', 'skill-postgres', 'skill-docker', 'skill-aws', 'skill-sql'],
  },
  {
    id: 'user-3',
    name: 'Marcus Johnson',
    email: 'marcus.j@example.com',
    skillIds: ['skill-node', 'skill-express', 'skill-ts', 'skill-postgres', 'skill-redis', 'skill-rest', 'skill-docker'],
  },
  {
    id: 'user-4',
    name: 'Elena Rostova',
    email: 'elena.rostova@example.com',
    skillIds: ['skill-docker', 'skill-k8s', 'skill-aws', 'skill-terraform', 'skill-cicd', 'skill-linux', 'skill-prometheus'],
  },
  {
    id: 'user-5',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    skillIds: ['skill-python', 'skill-pandas', 'skill-numpy', 'skill-sql', 'skill-postgres', 'skill-powerbi', 'skill-spark'],
  },
  {
    id: 'user-6',
    name: 'David Kim',
    email: 'david.kim@example.com',
    skillIds: ['skill-java', 'skill-spring', 'skill-sql', 'skill-postgres', 'skill-kafka', 'skill-microservices', 'skill-docker'],
  },
  {
    id: 'user-7',
    name: 'Chloe Bennett',
    email: 'chloe.b@example.com',
    skillIds: ['skill-js', 'skill-react', 'skill-redux', 'skill-html', 'skill-css', 'skill-testing'],
  },
  {
    id: 'user-8',
    name: 'Tariq Al-Mansoor',
    email: 'tariq.m@example.com',
    skillIds: ['skill-go', 'skill-grpc', 'skill-docker', 'skill-k8s', 'skill-redis', 'skill-postgres', 'skill-sysdesign'],
  },
  {
    id: 'user-9',
    name: 'Jessica Taylor',
    email: 'jessica.t@example.com',
    skillIds: ['skill-python', 'skill-pytorch', 'skill-tensorflow', 'skill-llm', 'skill-docker', 'skill-fastapi'],
  },
  {
    id: 'user-10',
    name: 'Lucas Silva',
    email: 'lucas.silva@example.com',
    skillIds: ['skill-js', 'skill-ts', 'skill-react', 'skill-node', 'skill-express', 'skill-postgres', 'skill-sql', 'skill-git'],
  },
  {
    id: 'user-11',
    name: 'Hannah Weber',
    email: 'hannah.weber@example.com',
    skillIds: ['skill-vue', 'skill-js', 'skill-ts', 'skill-tailwind', 'skill-html', 'skill-css'],
  },
  {
    id: 'user-12',
    name: 'Kenji Sato',
    email: 'kenji.sato@example.com',
    skillIds: ['skill-rust', 'skill-csharp', 'skill-dotnet', 'skill-sql', 'skill-docker', 'skill-sysdesign'],
  },
  {
    id: 'user-13',
    name: 'Amara Okafor',
    email: 'amara.okafor@example.com',
    skillIds: ['skill-aws', 'skill-gcp', 'skill-terraform', 'skill-linux', 'skill-docker', 'skill-cicd'],
  },
  {
    id: 'user-14',
    name: 'Mateo Hernandez',
    email: 'mateo.h@example.com',
    skillIds: ['skill-python', 'skill-django', 'skill-postgres', 'skill-redis', 'skill-rest', 'skill-docker'],
  },
  {
    id: 'user-15',
    name: 'Sophia Mueller',
    email: 'sophia.m@example.com',
    skillIds: ['skill-sql', 'skill-postgres', 'skill-tableau', 'skill-powerbi', 'skill-pandas', 'skill-python'],
  },
  {
    id: 'user-16',
    name: 'Liam O\'Connor',
    email: 'liam.oc@example.com',
    skillIds: ['skill-angular', 'skill-ts', 'skill-js', 'skill-html', 'skill-css', 'skill-rest'],
  },
  {
    id: 'user-17',
    name: 'Zoe Zhang',
    email: 'zoe.zhang@example.com',
    skillIds: ['skill-node', 'skill-nest', 'skill-ts', 'skill-graphql', 'skill-mongodb', 'skill-redis'],
  },
  {
    id: 'user-18',
    name: 'Devon Vance',
    email: 'devon.vance@example.com',
    skillIds: ['skill-neo4j', 'skill-sql', 'skill-python', 'skill-fastapi', 'skill-docker', 'skill-aws'],
  },
  {
    id: 'user-19',
    name: 'Aisha Patel',
    email: 'aisha.patel@example.com',
    skillIds: ['skill-js', 'skill-react', 'skill-nextjs', 'skill-node', 'skill-graphql', 'skill-tailwind'],
  },
  {
    id: 'user-20',
    name: 'Gabriel Costa',
    email: 'gabriel.costa@example.com',
    skillIds: ['skill-java', 'skill-spring', 'skill-microservices', 'skill-k8s', 'skill-aws', 'skill-kafka'],
  },
];

export const jobs: SeedJob[] = [
  // 1-15 Frontend & Fullstack Roles
  {
    id: 'job-1',
    title: 'Senior Frontend Engineer (React/Next.js)',
    description: 'Lead the frontend architecture of our core developer dashboard using Next.js, React, and TypeScript with ultra-fast edge rendering.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 160000,
    salaryMax: 210000,
    companyId: 'comp-vercel',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-react', 'skill-nextjs', 'skill-ts', 'skill-tailwind', 'skill-html', 'skill-css'],
  },
  {
    id: 'job-2',
    title: 'Frontend Developer',
    description: 'Build sleek, accessible UI components for our high-frequency payment checkout flows and merchant dashboard.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 130000,
    salaryMax: 165000,
    companyId: 'comp-stripe',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-react', 'skill-js', 'skill-ts', 'skill-css', 'skill-testing'],
  },
  {
    id: 'job-3',
    title: 'Full Stack Engineer (Node.js & React)',
    description: 'Own end-to-end features across our real-time collaboration canvas, bridging React state management with resilient Node.js microservices.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 140000,
    salaryMax: 180000,
    companyId: 'comp-figma',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-react', 'skill-node', 'skill-ts', 'skill-postgres', 'skill-rest'],
  },
  {
    id: 'job-4',
    title: 'Senior React Developer',
    description: 'Architect modular design systems and interactive UI modules for high-velocity project tracking.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 170000,
    salaryMax: 220000,
    companyId: 'comp-linear',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-react', 'skill-ts', 'skill-redux', 'skill-tailwind', 'skill-testing'],
  },
  {
    id: 'job-5',
    title: 'Junior Web Developer',
    description: 'Kickstart your career crafting interactive landing pages, documentation, and user portals.',
    employmentType: 'Full-time',
    experienceLevel: 'Entry',
    salaryMin: 85000,
    salaryMax: 110000,
    companyId: 'comp-supabase',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-html', 'skill-css', 'skill-js', 'skill-react', 'skill-git'],
  },
  {
    id: 'job-6',
    title: 'Staff Full Stack Developer',
    description: 'Drive high-throughput web applications and design resilient backend API systems serving millions of global merchants.',
    employmentType: 'Full-time',
    experienceLevel: 'Lead',
    salaryMin: 190000,
    salaryMax: 250000,
    companyId: 'comp-shopify',
    locationId: 'loc-tor',
    requiredSkillIds: ['skill-ts', 'skill-react', 'skill-node', 'skill-graphql', 'skill-postgres', 'skill-redis'],
  },
  {
    id: 'job-7',
    title: 'Frontend UI/UX Engineer',
    description: 'Craft responsive, intuitive interfaces with delightful micro-interactions for modern workspace software.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 135000,
    salaryMax: 175000,
    companyId: 'comp-notion',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-react', 'skill-ts', 'skill-tailwind', 'skill-css', 'skill-html'],
  },
  {
    id: 'job-8',
    title: 'Full Stack TypeScript Engineer',
    description: 'Work on developer tools, Git workflows, and CI/CD visualization tools with modern TypeScript across frontend and backend.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 165000,
    salaryMax: 215000,
    companyId: 'comp-github',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-ts', 'skill-react', 'skill-node', 'skill-docker', 'skill-rest'],
  },
  {
    id: 'job-9',
    title: 'Vue.js Frontend Specialist',
    description: 'Develop sophisticated customer-facing dashboards and shopping experiences across European e-commerce portals.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 110000,
    salaryMax: 140000,
    companyId: 'comp-zalando',
    locationId: 'loc-ber',
    requiredSkillIds: ['skill-vue', 'skill-js', 'skill-ts', 'skill-tailwind', 'skill-html'],
  },
  {
    id: 'job-10',
    title: 'Web Application Engineer',
    description: 'Scale modern audio web players, dynamic playlists, and recommendation surfaces.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 125000,
    salaryMax: 160000,
    companyId: 'comp-spotify',
    locationId: 'loc-lon',
    requiredSkillIds: ['skill-react', 'skill-ts', 'skill-redux', 'skill-rest', 'skill-testing'],
  },

  // 11-25 Backend & Microservices Roles
  {
    id: 'job-11',
    title: 'Backend Developer (Node.js & Express)',
    description: 'Build robust REST APIs and event-driven data streaming services for financial account aggregations.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 135000,
    salaryMax: 170000,
    companyId: 'comp-plaid',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-node', 'skill-express', 'skill-ts', 'skill-postgres', 'skill-sql', 'skill-rest'],
  },
  {
    id: 'job-12',
    title: 'Senior Backend Engineer (Python & FastAPI)',
    description: 'Scale our generative AI inference pipelines, prompt routing, and low-latency API gateways.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 180000,
    salaryMax: 240000,
    companyId: 'comp-openai',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-python', 'skill-fastapi', 'skill-redis', 'skill-postgres', 'skill-docker', 'skill-sysdesign'],
  },
  {
    id: 'job-13',
    title: 'Java Backend Engineer',
    description: 'Design distributed transaction processing systems with Spring Boot and Kafka handling billions in daily payment volume.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 170000,
    salaryMax: 220000,
    companyId: 'comp-stripe',
    locationId: 'loc-ny',
    requiredSkillIds: ['skill-java', 'skill-spring', 'skill-sql', 'skill-postgres', 'skill-kafka', 'skill-microservices'],
  },
  {
    id: 'job-14',
    title: 'Go Systems Engineer',
    description: 'Develop low-latency networking, DNS caching, and edge routing engines running on millions of bare-metal servers.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 175000,
    salaryMax: 230000,
    companyId: 'comp-cloudflare',
    locationId: 'loc-aus',
    requiredSkillIds: ['skill-go', 'skill-grpc', 'skill-linux', 'skill-docker', 'skill-sysdesign'],
  },
  {
    id: 'job-15',
    title: 'NestJS Backend Architect',
    description: 'Build enterprise-grade microservices with NestJS, GraphQL, and Redis caching for banking services.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 150000,
    salaryMax: 195000,
    companyId: 'comp-revolut',
    locationId: 'loc-lon',
    requiredSkillIds: ['skill-nest', 'skill-node', 'skill-ts', 'skill-graphql', 'skill-postgres', 'skill-redis'],
  },
  {
    id: 'job-16',
    title: 'Python Backend Developer (Django)',
    description: 'Maintain and scale backend booking algorithms, trust & safety heuristics, and dynamic pricing APIs.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 130000,
    salaryMax: 165000,
    companyId: 'comp-airbnb',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-python', 'skill-django', 'skill-postgres', 'skill-redis', 'skill-rest'],
  },
  {
    id: 'job-17',
    title: 'Distributed Systems Engineer (Go & gRPC)',
    description: 'Build core dispatch algorithms and real-time fleet telematics using Go, Kafka, and Redis.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 170000,
    salaryMax: 225000,
    companyId: 'comp-uber',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-go', 'skill-grpc', 'skill-kafka', 'skill-redis', 'skill-microservices'],
  },
  {
    id: 'job-18',
    title: 'Node.js Developer',
    description: 'Create fast GraphQL APIs and event streams powering on-demand delivery logistics.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 110000,
    salaryMax: 145000,
    companyId: 'comp-swiggy',
    locationId: 'loc-blr',
    requiredSkillIds: ['skill-node', 'skill-express', 'skill-mongodb', 'skill-redis', 'skill-rest'],
  },
  {
    id: 'job-19',
    title: 'C# / .NET Core Software Engineer',
    description: 'Modernize enterprise analytics engines with .NET Core, SQL Server, and microservices.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 125000,
    salaryMax: 160000,
    companyId: 'comp-palantir',
    locationId: 'loc-ny',
    requiredSkillIds: ['skill-csharp', 'skill-dotnet', 'skill-sql', 'skill-docker', 'skill-rest'],
  },
  {
    id: 'job-20',
    title: 'Database & Graph Solutions Engineer',
    description: 'Help developers harness graph relationships, Cypher queries, and graph database algorithms.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 155000,
    salaryMax: 200000,
    companyId: 'comp-supabase',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-neo4j', 'skill-sql', 'skill-postgres', 'skill-python', 'skill-rest'],
  },

  // 21-35 DevOps, Cloud & Infrastructure
  {
    id: 'job-21',
    title: 'DevOps Engineer (Kubernetes & AWS)',
    description: 'Scale multi-tenant Kubernetes clusters on AWS, automate infrastructure with Terraform, and enforce zero-trust security.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 160000,
    salaryMax: 210000,
    companyId: 'comp-datadog',
    locationId: 'loc-ny',
    requiredSkillIds: ['skill-docker', 'skill-k8s', 'skill-aws', 'skill-terraform', 'skill-cicd', 'skill-linux'],
  },
  {
    id: 'job-22',
    title: 'Cloud Infrastructure Engineer',
    description: 'Build next-generation multi-cloud provisioning tools and Terraform providers.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 170000,
    salaryMax: 220000,
    companyId: 'comp-hashicorp',
    locationId: 'loc-sea',
    requiredSkillIds: ['skill-terraform', 'skill-aws', 'skill-gcp', 'skill-docker', 'skill-linux', 'skill-go'],
  },
  {
    id: 'job-23',
    title: 'Site Reliability Engineer (SRE)',
    description: 'Ensure 99.999% availability of crypto brokerage and trading infrastructure with Prometheus, Grafana, and Kubernetes.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 175000,
    salaryMax: 230000,
    companyId: 'comp-coinbase',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-k8s', 'skill-aws', 'skill-prometheus', 'skill-linux', 'skill-docker', 'skill-cicd'],
  },
  {
    id: 'job-24',
    title: 'Junior DevOps Engineer',
    description: 'Manage automated test suites, CI/CD runners, and Dockerized staging environments.',
    employmentType: 'Full-time',
    experienceLevel: 'Entry',
    salaryMin: 90000,
    salaryMax: 115000,
    companyId: 'comp-shopify',
    locationId: 'loc-tor',
    requiredSkillIds: ['skill-docker', 'skill-linux', 'skill-cicd', 'skill-git', 'skill-aws'],
  },
  {
    id: 'job-25',
    title: 'Platform Engineer (GCP & Kubernetes)',
    description: 'Deliver self-service developer platforms and automated telemetry across international engineering hubs.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 140000,
    salaryMax: 180000,
    companyId: 'comp-spotify',
    locationId: 'loc-lon',
    requiredSkillIds: ['skill-gcp', 'skill-k8s', 'skill-docker', 'skill-terraform', 'skill-cicd'],
  },

  // 26-40 Data Engineering, Analytics & AI
  {
    id: 'job-26',
    title: 'Senior Data Engineer (Spark & Python)',
    description: 'Architect petabyte-scale streaming pipelines, data lake tables, and automated analytical marts.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 165000,
    salaryMax: 215000,
    companyId: 'comp-databricks',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-python', 'skill-spark', 'skill-sql', 'skill-postgres', 'skill-pandas', 'skill-aws'],
  },
  {
    id: 'job-27',
    title: 'Data Analyst (SQL & Power BI)',
    description: 'Transform complex payment metrics into actionable business intelligence dashboards for executive leadership.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 105000,
    salaryMax: 135000,
    companyId: 'comp-stripe',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-sql', 'skill-powerbi', 'skill-pandas', 'skill-postgres'],
  },
  {
    id: 'job-28',
    title: 'Machine Learning Research Engineer',
    description: 'Train and fine-tune large multimodal models, implement RLHF alignment algorithms, and optimize token throughput.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 210000,
    salaryMax: 300000,
    companyId: 'comp-anthropic',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-python', 'skill-pytorch', 'skill-llm', 'skill-numpy', 'skill-docker'],
  },
  {
    id: 'job-29',
    title: 'Cloud Data Warehouse Architect',
    description: 'Design zero-copy data sharing schemas and scalable query workloads on modern cloud warehouses.',
    employmentType: 'Full-time',
    experienceLevel: 'Lead',
    salaryMin: 185000,
    salaryMax: 245000,
    companyId: 'comp-snowflake',
    locationId: 'loc-aus',
    requiredSkillIds: ['skill-sql', 'skill-python', 'skill-aws', 'skill-postgres', 'skill-sysdesign'],
  },
  {
    id: 'job-30',
    title: 'Business Intelligence & Tableau Specialist',
    description: 'Build predictive retention models and interactive visual stories for marketing and growth teams.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 100000,
    salaryMax: 130000,
    companyId: 'comp-airbnb',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-tableau', 'skill-sql', 'skill-pandas', 'skill-python'],
  },

  // 31-45 Additional Specialized & Diverse Roles
  {
    id: 'job-31',
    title: 'Lead Software Architect',
    description: 'Spearhead architectural standards across all distributed services, ensuring resilient system design and minimal latency.',
    employmentType: 'Full-time',
    experienceLevel: 'Lead',
    salaryMin: 220000,
    salaryMax: 280000,
    companyId: 'comp-uber',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-sysdesign', 'skill-microservices', 'skill-go', 'skill-k8s', 'skill-kafka'],
  },
  {
    id: 'job-32',
    title: 'Software Engineer - Developer Experience',
    description: 'Build internal CLI tooling, automated preview environments, and rapid build pipelines.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 140000,
    salaryMax: 175000,
    companyId: 'comp-github',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-ts', 'skill-node', 'skill-git', 'skill-docker', 'skill-testing'],
  },
  {
    id: 'job-33',
    title: 'Full Stack Python & React Developer',
    description: 'Develop intelligent workspace applications connecting AI assistants with user databases and notebooks.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 145000,
    salaryMax: 185000,
    companyId: 'comp-notion',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-react', 'skill-python', 'skill-fastapi', 'skill-ts', 'skill-postgres'],
  },
  {
    id: 'job-34',
    title: 'Backend API Engineer (REST & GraphQL)',
    description: 'Create ultra-fast public and partner APIs with automated schema validation and rate limiting.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 130000,
    salaryMax: 165000,
    companyId: 'comp-linear',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-node', 'skill-graphql', 'skill-rest', 'skill-ts', 'skill-postgres'],
  },
  {
    id: 'job-35',
    title: 'Senior Java / Spring Cloud Engineer',
    description: 'Maintain high-concurrency microservices with Spring Cloud, Docker, and PostgreSQL.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 160000,
    salaryMax: 205000,
    companyId: 'comp-revolut',
    locationId: 'loc-lon',
    requiredSkillIds: ['skill-java', 'skill-spring', 'skill-postgres', 'skill-docker', 'skill-microservices'],
  },
  {
    id: 'job-36',
    title: 'DevOps & Security Automation Specialist',
    description: 'Integrate automated vulnerability scanning, container signing, and IAM governance into GitLab and GitHub Actions.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 165000,
    salaryMax: 215000,
    companyId: 'comp-cloudflare',
    locationId: 'loc-aus',
    requiredSkillIds: ['skill-docker', 'skill-k8s', 'skill-linux', 'skill-cicd', 'skill-aws'],
  },
  {
    id: 'job-37',
    title: 'Frontend Engineer (Design Systems)',
    description: 'Build open-source UI component libraries and accessible design token systems.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 135000,
    salaryMax: 170000,
    companyId: 'comp-figma',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-react', 'skill-ts', 'skill-tailwind', 'skill-html', 'skill-css'],
  },
  {
    id: 'job-38',
    title: 'AI Application Engineer (LangChain & Python)',
    description: 'Build production RAG pipelines, vector search integrations, and agent workflows for enterprise clients.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 175000,
    salaryMax: 230000,
    companyId: 'comp-openai',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-python', 'skill-llm', 'skill-fastapi', 'skill-docker', 'skill-redis'],
  },
  {
    id: 'job-39',
    title: 'Data Infrastructure Engineer (Kafka & Redis)',
    description: 'Scale low-latency event ingestion clusters processing millions of events per second.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 170000,
    salaryMax: 220000,
    companyId: 'comp-datadog',
    locationId: 'loc-ny',
    requiredSkillIds: ['skill-kafka', 'skill-redis', 'skill-linux', 'skill-k8s', 'skill-sysdesign'],
  },
  {
    id: 'job-40',
    title: 'Junior Full Stack Developer',
    description: 'Collaborate with senior mentors to deliver customer-facing dashboard features and API endpoints.',
    employmentType: 'Full-time',
    experienceLevel: 'Entry',
    salaryMin: 85000,
    salaryMax: 110000,
    companyId: 'comp-zalando',
    locationId: 'loc-ber',
    requiredSkillIds: ['skill-js', 'skill-node', 'skill-react', 'skill-sql', 'skill-git'],
  },

  // 41-75 Rich Variety across Levels & Cities
  {
    id: 'job-41',
    title: 'Senior Next.js Full Stack Engineer',
    description: 'Deliver serverless React applications with Next.js 14 App Router, edge middleware, and Postgres.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 165000,
    salaryMax: 210000,
    companyId: 'comp-vercel',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-nextjs', 'skill-react', 'skill-ts', 'skill-postgres', 'skill-tailwind'],
  },
  {
    id: 'job-42',
    title: 'Cloud Security Engineer',
    description: 'Enforce perimeter security, automated compliance checks, and AWS IAM policies.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 160000,
    salaryMax: 210000,
    companyId: 'comp-coinbase',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-aws', 'skill-linux', 'skill-terraform', 'skill-docker', 'skill-cicd'],
  },
  {
    id: 'job-43',
    title: 'Data Science & Machine Learning Engineer',
    description: 'Deploy machine learning classification models and automated retraining pipelines for logistics optimization.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 140000,
    salaryMax: 180000,
    companyId: 'comp-swiggy',
    locationId: 'loc-blr',
    requiredSkillIds: ['skill-python', 'skill-pandas', 'skill-numpy', 'skill-pytorch', 'skill-sql'],
  },
  {
    id: 'job-44',
    title: 'Contract Frontend Developer (Vue / Nuxt)',
    description: 'Short-term contract to modernize legacy frontend views into reactive Vue components.',
    employmentType: 'Contract',
    experienceLevel: 'Mid',
    salaryMin: 90000,
    salaryMax: 120000,
    companyId: 'comp-zalando',
    locationId: 'loc-ber',
    requiredSkillIds: ['skill-vue', 'skill-js', 'skill-html', 'skill-css'],
  },
  {
    id: 'job-45',
    title: 'Backend Systems Engineer (Rust)',
    description: 'High-performance cryptography and core ledger engine development in Rust.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 190000,
    salaryMax: 250000,
    companyId: 'comp-coinbase',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-rust', 'skill-linux', 'skill-docker', 'skill-sysdesign'],
  },
  {
    id: 'job-46',
    title: 'Full Stack Web Developer (Express + React)',
    description: 'Build client dashboards and administrative tools for e-commerce store owners.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 120000,
    salaryMax: 155000,
    companyId: 'comp-shopify',
    locationId: 'loc-tor',
    requiredSkillIds: ['skill-react', 'skill-express', 'skill-node', 'skill-sql', 'skill-tailwind'],
  },
  {
    id: 'job-47',
    title: 'Senior Observability Engineer',
    description: 'Build high-throughput telemetry ingestion with Prometheus, Grafana, and Go.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 165000,
    salaryMax: 215000,
    companyId: 'comp-datadog',
    locationId: 'loc-ny',
    requiredSkillIds: ['skill-prometheus', 'skill-k8s', 'skill-docker', 'skill-go', 'skill-linux'],
  },
  {
    id: 'job-48',
    title: 'Data Analyst - Growth & Monetization',
    description: 'Run A/B testing analysis and build executive data dashboards in Power BI and SQL.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 110000,
    salaryMax: 140000,
    companyId: 'comp-spotify',
    locationId: 'loc-lon',
    requiredSkillIds: ['skill-sql', 'skill-powerbi', 'skill-pandas', 'skill-python'],
  },
  {
    id: 'job-49',
    title: 'Lead Cloud Architect (Azure & Kubernetes)',
    description: 'Guide enterprise clients on multi-region Azure architecture and container orchestration.',
    employmentType: 'Full-time',
    experienceLevel: 'Lead',
    salaryMin: 195000,
    salaryMax: 255000,
    companyId: 'comp-hashicorp',
    locationId: 'loc-sea',
    requiredSkillIds: ['skill-azure', 'skill-k8s', 'skill-terraform', 'skill-docker', 'skill-sysdesign'],
  },
  {
    id: 'job-50',
    title: 'Senior React Native / React Engineer',
    description: 'Develop multi-platform mobile and web client interfaces for global travelers.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 160000,
    salaryMax: 210000,
    companyId: 'comp-airbnb',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-react', 'skill-ts', 'skill-js', 'skill-redux', 'skill-testing'],
  },
  {
    id: 'job-51',
    title: 'Golang Microservices Developer',
    description: 'Implement distributed microservices for payment routing and tokenization.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 140000,
    salaryMax: 180000,
    companyId: 'comp-stripe',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-go', 'skill-grpc', 'skill-postgres', 'skill-docker', 'skill-microservices'],
  },
  {
    id: 'job-52',
    title: 'Frontend Engineer (Next.js & Tailwind)',
    description: 'Craft responsive landing pages, interactive product documentation, and interactive playground widgets.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 125000,
    salaryMax: 160000,
    companyId: 'comp-supabase',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-nextjs', 'skill-react', 'skill-tailwind', 'skill-ts', 'skill-html'],
  },
  {
    id: 'job-53',
    title: 'Senior Postgres Database Administrator',
    description: 'Tune high-load Postgres clusters, configure replication, and implement automated point-in-time backups.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 160000,
    salaryMax: 210000,
    companyId: 'comp-supabase',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-postgres', 'skill-sql', 'skill-linux', 'skill-docker', 'skill-sysdesign'],
  },
  {
    id: 'job-54',
    title: 'Machine Learning Ops Engineer (MLOps)',
    description: 'Automate model training workflows, model registry, and GPU cluster scheduling on Kubernetes.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 180000,
    salaryMax: 235000,
    companyId: 'comp-databricks',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-k8s', 'skill-docker', 'skill-python', 'skill-pytorch', 'skill-aws'],
  },
  {
    id: 'job-55',
    title: 'Angular Frontend Engineer',
    description: 'Build enterprise administrative dashboards with Angular, TypeScript, and RxJS.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 115000,
    salaryMax: 150000,
    companyId: 'comp-palantir',
    locationId: 'loc-ny',
    requiredSkillIds: ['skill-angular', 'skill-ts', 'skill-js', 'skill-html', 'skill-css'],
  },
  {
    id: 'job-56',
    title: 'Junior Python Developer',
    description: 'Write automated scrapers, data cleaning scripts, and internal Flask/FastAPI micro-endpoints.',
    employmentType: 'Full-time',
    experienceLevel: 'Entry',
    salaryMin: 80000,
    salaryMax: 105000,
    companyId: 'comp-plaid',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-python', 'skill-sql', 'skill-git', 'skill-rest', 'skill-pandas'],
  },
  {
    id: 'job-57',
    title: 'Staff Infrastructure Architect',
    description: 'Architect global edge compute deployments across 300+ cities with Terraform and Go.',
    employmentType: 'Full-time',
    experienceLevel: 'Lead',
    salaryMin: 210000,
    salaryMax: 270000,
    companyId: 'comp-cloudflare',
    locationId: 'loc-aus',
    requiredSkillIds: ['skill-terraform', 'skill-go', 'skill-linux', 'skill-docker', 'skill-sysdesign'],
  },
  {
    id: 'job-58',
    title: 'Senior Software Engineer (Search & Elasticsearch)',
    description: 'Optimize high-speed catalog search, semantic indexing, and autocomplete queries.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 165000,
    salaryMax: 215000,
    companyId: 'comp-zalando',
    locationId: 'loc-ber',
    requiredSkillIds: ['skill-elastic', 'skill-java', 'skill-postgres', 'skill-docker', 'skill-microservices'],
  },
  {
    id: 'job-59',
    title: 'Full Stack Engineer (GraphQL & React)',
    description: 'Design intuitive workspace collaboration surfaces powered by end-to-end type safe GraphQL.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 140000,
    salaryMax: 175000,
    companyId: 'comp-notion',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-react', 'skill-graphql', 'skill-ts', 'skill-node', 'skill-postgres'],
  },
  {
    id: 'job-60',
    title: 'Senior Security Operations Engineer',
    description: 'Implement automated incident response playbooks, SIEM detection rules, and cloud posture monitoring.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 160000,
    salaryMax: 205000,
    companyId: 'comp-datadog',
    locationId: 'loc-ny',
    requiredSkillIds: ['skill-aws', 'skill-linux', 'skill-python', 'skill-docker', 'skill-k8s'],
  },
  {
    id: 'job-61',
    title: 'QA & Test Automation Lead',
    description: 'Build comprehensive end-to-end testing frameworks with Playwright, Jest, and CI/CD automation.',
    employmentType: 'Full-time',
    experienceLevel: 'Lead',
    salaryMin: 150000,
    salaryMax: 190000,
    companyId: 'comp-figma',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-testing', 'skill-ts', 'skill-js', 'skill-cicd', 'skill-git'],
  },
  {
    id: 'job-62',
    title: 'Senior Redis & Cache Architect',
    description: 'Optimize ultra-low latency caching layers, session stores, and rate limiters.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 165000,
    salaryMax: 215000,
    companyId: 'comp-uber',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-redis', 'skill-go', 'skill-microservices', 'skill-sysdesign', 'skill-linux'],
  },
  {
    id: 'job-63',
    title: 'AI Alignment & Safety Engineer',
    description: 'Develop testing suites and red-teaming harnesses for frontier LLMs.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 190000,
    salaryMax: 260000,
    companyId: 'comp-anthropic',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-python', 'skill-llm', 'skill-pytorch', 'skill-testing'],
  },
  {
    id: 'job-64',
    title: 'Solutions Architect (Fintech APIs)',
    description: 'Partner with enterprise engineering teams to integrate open banking APIs and webhooks.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 155000,
    salaryMax: 200000,
    companyId: 'comp-plaid',
    locationId: 'loc-ny',
    requiredSkillIds: ['skill-rest', 'skill-node', 'skill-sql', 'skill-sysdesign'],
  },
  {
    id: 'job-65',
    title: 'Senior Frontend Developer (Performance & WebGL)',
    description: 'Push browser rendering performance to 60fps for complex vector design and animation tools.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 175000,
    salaryMax: 225000,
    companyId: 'comp-figma',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-ts', 'skill-react', 'skill-js', 'skill-testing', 'skill-css'],
  },
  {
    id: 'job-66',
    title: 'Data Platform Engineer (Snowflake & Python)',
    description: 'Build reliable ETL pipelines moving terabytes of marketing and sales data into Snowflake.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 135000,
    salaryMax: 175000,
    companyId: 'comp-snowflake',
    locationId: 'loc-aus',
    requiredSkillIds: ['skill-sql', 'skill-python', 'skill-pandas', 'skill-aws', 'skill-cicd'],
  },
  {
    id: 'job-67',
    title: 'Backend Engineer (FastAPI & Docker)',
    description: 'Scale asynchronous Python services for payment fraud prevention and live transaction monitoring.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 135000,
    salaryMax: 170000,
    companyId: 'comp-revolut',
    locationId: 'loc-lon',
    requiredSkillIds: ['skill-python', 'skill-fastapi', 'skill-postgres', 'skill-docker', 'skill-redis'],
  },
  {
    id: 'job-68',
    title: 'Junior Cloud Operations Associate',
    description: 'Monitor cloud alarms, maintain backup health, and assist with deployment runbooks.',
    employmentType: 'Full-time',
    experienceLevel: 'Entry',
    salaryMin: 80000,
    salaryMax: 100000,
    companyId: 'comp-hashicorp',
    locationId: 'loc-sea',
    requiredSkillIds: ['skill-aws', 'skill-linux', 'skill-docker', 'skill-git'],
  },
  {
    id: 'job-69',
    title: 'Lead Full Stack Architect',
    description: 'Direct the technical roadmap for cloud developer platform features from CLI to web UI.',
    employmentType: 'Full-time',
    experienceLevel: 'Lead',
    salaryMin: 220000,
    salaryMax: 290000,
    companyId: 'comp-vercel',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-nextjs', 'skill-react', 'skill-ts', 'skill-node', 'skill-sysdesign'],
  },
  {
    id: 'job-70',
    title: 'Senior Software Engineer (Data Products)',
    description: 'Build high-performance interactive query systems over massive graph and tabular datasets.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 170000,
    salaryMax: 220000,
    companyId: 'comp-palantir',
    locationId: 'loc-ny',
    requiredSkillIds: ['skill-java', 'skill-ts', 'skill-react', 'skill-sql', 'skill-sysdesign'],
  },
  {
    id: 'job-71',
    title: 'DevOps Engineer (GCP & Terraform)',
    description: 'Automate multi-region GCP infrastructure provisioning with Terraform, Vault, and GitHub Actions.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 140000,
    salaryMax: 180000,
    companyId: 'comp-linear',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-gcp', 'skill-terraform', 'skill-docker', 'skill-cicd', 'skill-linux'],
  },
  {
    id: 'job-72',
    title: 'Senior Full Stack Engineer (Python & Vue)',
    description: 'Deliver responsive e-commerce management consoles with Vue 3, Tailwind, and FastAPI backends.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 155000,
    salaryMax: 195000,
    companyId: 'comp-zalando',
    locationId: 'loc-ber',
    requiredSkillIds: ['skill-vue', 'skill-python', 'skill-fastapi', 'skill-tailwind', 'skill-postgres'],
  },
  {
    id: 'job-73',
    title: 'Distributed Storage Engineer',
    description: 'Build zero-trust encrypted object storage and distributed replication systems in Rust and Go.',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 185000,
    salaryMax: 240000,
    companyId: 'comp-cloudflare',
    locationId: 'loc-aus',
    requiredSkillIds: ['skill-rust', 'skill-go', 'skill-sysdesign', 'skill-linux', 'skill-docker'],
  },
  {
    id: 'job-74',
    title: 'AI Data Analyst (Python & Spark)',
    description: 'Analyze user behavior trajectories, evaluate model performance regressions, and maintain data pipelines.',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    salaryMin: 125000,
    salaryMax: 165000,
    companyId: 'comp-openai',
    locationId: 'loc-sf',
    requiredSkillIds: ['skill-python', 'skill-spark', 'skill-pandas', 'skill-sql', 'skill-postgres'],
  },
  {
    id: 'job-75',
    title: 'Staff Graph Database Engineer',
    description: 'Design advanced graph querying algorithms, knowledge graphs, and recommendation engines on Neo4j/CognoDB.',
    employmentType: 'Full-time',
    experienceLevel: 'Lead',
    salaryMin: 200000,
    salaryMax: 260000,
    companyId: 'comp-supabase',
    locationId: 'loc-rem',
    requiredSkillIds: ['skill-neo4j', 'skill-sql', 'skill-sysdesign', 'skill-python', 'skill-ts'],
  },
];
